### ISSUE TITLE
Why all the test requirements when no tests are run?

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/datashader-feedstock#3]
Can anyone explain this?

```
test:
  requires:
    - pytest >=2.8.5
    - pytest-benchmark >=3.0.0
    - rasterio
    - scipy
  imports:
    - datashader
```
